apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-94"
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: cert-manager
