controller:
  config:
    use-proxy-protocol: "false"
    enable-real-ip: "true"
  hostPort:
    enabled: true
  ingressClassResource:
    default: true
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false # we don't have prometheus operator yet
  service:
    type: ClusterIP
  watchIngressWithoutClass: true
defaultBackend:
  enabled: true
  image:
    registry: docker.io
    image: sikalabs/sikalabs-kubernetes-homepage
    tag: latest
  extraEnvs:
    - name: CLUSTER
      value: "pss"
    - name: DOMAIN
      value: "jos.sikademo.com"
  port: 8000
