configs:
  cm:
    url: https://argocd.lab0.sikademo.com
    exec.enabled: "true"
    oidc.config: |
      name: SSO
      issuer: https://sso.sikalabs.com/realms/training
      clientID: example_client_id
      clientSecret: example_client_secret
      requestedScopes: ["openid", "profile", "email", "groups"]
      logoutURL: "https://sso.sikalabs.com/realms/training/protocol/openid-connect/logout?client_id=example_client_id&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.lab0.sikademo.com"
  rbac:
    scopes: '[groups]'
    policy.default: ""
    policy.csv: |
      g, argocd-admins, role:admin
server:
  ingress:
    enabled: true
    hostname: argocd.lab0.sikademo.com
    tls: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
