apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  provider:
    vault:
      server: "https://vault-akcenta.panda.k8s.sl.zone"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets-operator"
          key: "vault-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
type: Opaque
stringData:
  vault-token: root
