# https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
# https://artifacthub.io/packages/helm/grafana/k8s-monitoring?modal=values

---
cluster:
  name: loki-training-cluster

destinations:
  - name: loki-single
    type: loki
    url: http://loki-single.loki-single.svc.cluster.local:3100/loki/api/v1/push
  - name: loki-scalable
    type: loki
    url: http://loki-scalable-gateway.loki-scalable.svc.cluster.local/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
    - argocd
    - grafana
    - hello-world
    - ingress-nginx
    - loki-scalable
    - loki-single
    - minio
    - signpost

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
  structuredMetadata:
    pod: pod  # Set structured metadata "pod" from label "pod"
  namespaces:
    - argocd
    - grafana
    - hello-world
    - ingress-nginx
    - loki-scalable
    - loki-single
    - minio
    - signpost

# Collectors
alloy-singleton:
  enabled: false

alloy-metrics:
  enabled: false

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    mounts:
      varlog: false
    clustering:
      enabled: true

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false
